import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const dictionary = {
  vi: {
    // Navbar
    brandTitle: "AgriGuard-IoT",
    brandSubtitle: "Hệ thống Ra quyết định Nông học Thông minh",
    tabDashboard: "Bảng Điều Khiển Realtime",
    tabBatch: "Quét Lô Big Data CSV",
    tabAcademic: "Báo Cáo Đối Chứng Học Thuật",
    tabMobile: "Trạm Thực Địa Di Động (QR)",
    btnDemoLogin: "Đăng Nhập Nhanh",
    demoMenuTitle: "Demo 1-Chạm Theo Vai Trò",
    btnLogout: "Đăng Xuất",
    roleAdmin: "Admin",
    roleEngineer: "Kỹ sư Nông học",
    roleFarmer: "Nông dân",
    roleGuest: "Khách Xem",
    authSignInRegister: "Đăng Nhập / Đăng Ký",
    authSignIn: "Đăng Nhập",
    authRegister: "Đăng Ký Tài Khoản",
    switchThemeTitle: "Sáng / Tối Theme",
    switchLangTitle: "Đổi Ngôn Ngữ / Switch Language",

    // Auth Modal
    authModalTitleLogin: "Đăng Nhập Hệ Thống",
    authModalTitleRegister: "Tạo Tài Khoản Mới",
    authModalSubtitle: "Phân quyền theo vai trò: Admin, Kỹ sư Nông học hoặc Nông dân",
    authEmailLabel: "Địa chỉ Email",
    authPasswordLabel: "Mật khẩu",
    authFullNameLabel: "Họ và Tên",
    authRoleLabel: "Vai trò trong hệ thống",
    authBtnLogin: "Đăng Nhập",
    authBtnRegister: "Đăng Ký",
    authNoAccount: "Chưa có tài khoản?",
    authHaveAccount: "Đã có tài khoản?",
    authSwitchToRegister: "Đăng ký ngay",
    authSwitchToLogin: "Đăng nhập ngay",
    authDemoTitle: "Hoặc đăng nhập nhanh 1-chạm (Dành cho Giám khảo / Demo):",
    authLoginSuccess: "Đăng nhập thành công!",
    authRegisterSuccess: "Đăng ký thành công! Đang tự động đăng nhập...",

    // Dashboard Hero & Gauge
    heroTitle: "Giám Sát Stress Sinh Thái Cây Trồng Thời Gian Thực",
    heroDesc: "Kết hợp 9 kênh cảm biến vật lý, mô hình LightGBM tối ưu ngưỡng T*=0.34 và giao thức can thiệp nông học tức thì.",
    riskGaugeTitle: "Chỉ Số Nguy Cơ Stress Sinh Thái",
    statusOptimal: "SINH TRƯỞNG TỐI ƯU",
    statusWarning: "CẢNH BÁO SỚM — SUY THOÁI",
    statusCritical: "BÁO ĐỘNG ĐỎ — CẦN CỨU CÂY!",
    statusOptimalDesc: "Tất cả các chỉ số đều trong vùng sinh thái an toàn",
    statusWarningDesc: "Hệ sinh thái đang dần xấu đi, cần theo dõi sát",
    statusCriticalDesc: "Ngưỡng nguy cấp! Rễ cây hoặc tế bào đang tổn thương",
    stressProbLabel: "Xác Suất Stress Dự Đoán",
    execTimeLabel: "Thời Gian Xử Lý AI",
    gaugeDetailsBtn: "Chi tiết",
    gaugeLatencyExpl: "Là độ trễ tính toán thực tế của Python Backend khi nhận 9 thông số cảm biến, tính toán 4 chỉ số sinh thái nông học và chạy suy luận ma trận trọng số.",
    gaugeModelExplTitle: "Phân định mô hình:",
    gaugeModelExplLgb: "Tối ưu hóa xác suất liên tục trên tập Eco-Stress, phân dải xác suất mịn (18% - 54%).",
    gaugeModelExplSpark: "Huấn luyện phân tán trên 6 Partitions, hàm mất mát Log-loss phân cực mạnh mẽ (1.4% - 96.6%).",

    // Sliders
    slidersTitle: "9 Kênh Cảm Biến Sinh Thái Thực Địa",
    slidersDesc: "Kéo trượt để mô phỏng sự biến thiên của vi khí hậu hoặc chọn kịch bản mẫu.",
    slidersReadOnly: "Chỉ Xem (Quyền Nông Dân)",
    presetOptimal: "🌱 Tối Ưu",
    presetAcidic: "🍋 Đất Chua",
    presetHeatwave: "🔥 Hạn & Sốc Nhiệt",
    presetFlood: "🌊 Ngập Úng",
    soilPh: "Độ pH Đất",
    soilMoisture: "Độ Ẩm Đất",
    airTemp: "Nhiệt Độ Không Khí",
    sunlight: "Số Giờ Nắng",
    pollution: "Chỉ Số Ô Nhiễm",
    vegDensity: "Mật Độ Thảm Thực Vật",
    proximityWater: "Khoảng Cách Đến Nước",
    elevation: "Độ Cao Địa Hình",
    season: "Mùa Vụ",
    plantSpecies: "Loài Cây Trồng",
    unitHoursPerDay: "h/ngày",
    outOfBoundsWarning: "⚠️ Ngoài biên an toàn",
    bioOptimalSafe: "Chuẩn sinh học",
    seasonSpring: "🌸 Mùa Xuân (Spring)",
    seasonSummer: "☀️ Mùa Hè (Summer)",
    seasonAutumn: "🍂 Mùa Thu (Autumn)",
    seasonWinter: "❄️ Mùa Đông (Winter)",
    cropRice: "🌾 Lúa nước (Wetland C)",
    cropFruit: "🍎 Cây ăn trái (Tree Y)",
    cropVegetables: "🥦 Rau màu thổ nhưỡng (Shrub X)",
    cropGrass: "🌿 Đồng cỏ chăn nuôi (Grassland B)",

    // Root Cause & Prescription
    rootCauseTitle: "Chẩn Đoán Bắt Bệnh & Phác Đồ Can Thiệp",
    rootCauseSubtitle: "Hệ thống suy luận nhân quả và phác đồ can thiệp nông học tức thì",
    rootCauseHeader: "Nguyên Nhân Gốc Rễ Phát Hiện",
    remediationHeader: "Phác Đồ Điều Trị Nông Học",
    optimalStateCardTitle: "Trạng Thái Sinh Trưởng Lý Tưởng (0 Phát Hiện Stress)",
    optimalStateCardDesc: "Tất cả các chỉ số hóa sinh (pH đất, độ ẩm) và tiểu khí hậu vi sinh đều nằm trong vùng sinh thái an toàn. Không phát hiện dấu hiệu gây hại cho cây.",
    zeroCausesSafe: "0 Nguyên Nhân Gốc Rễ (An toàn)",
    causesDetectedSuffix: "Nguy cơ phát hiện",
    actuatorsSectionTitle: "Thiết Bị Cứu Cây Trực Tiếp (Actuators)",
    actuatorsRoleReq: "Yêu cầu quyền Kỹ Sư / Admin",
    btnTriggerMisting: "Bật Phun Sương Làm Mát",
    btnTriggerPump: "Kích Hoạt Máy Bơm Tưới",
    btnTriggerDrainage: "Tiêu Úng Khẩn Cấp",
    btnTriggerAlert: "Phát Cảnh Báo Âm Thanh",
    actuatorSending: "Đang gửi lệnh...",
    actuatorOpeningValve: "Đang mở van...",
    actuatorBroadcasting: "Đang phát...",
    toastOptimalWarn: "⚠️ Cây trồng đang ở trạng thái tối ưu lý tưởng! Không cần thiết phải kích hoạt thiết bị cứu cây lúc này (tránh lãng phí tài nguyên và làm xáo trộn vi khí hậu).",
    toastFloodMismatch: "❌ Cảnh báo sai phác đồ: Đất đang ngập úng nghiêm trọng, bơm tưới thêm nước sẽ làm chết rễ! Bạn cần kích hoạt 'Máy Bơm Tiêu Úng & Van Xả Rãnh'.",
    toastDroughtMismatch: "❌ Cảnh báo sai phác đồ: Đất đang bị hạn hán khô kiệt, xả nước sẽ làm kiệt nguồn nước! Cần kích hoạt 'Máy Bơm Tưới Nhỏ Giọt' hoặc 'Phun Sương Làm Mát'.",
    toastAcidityMismatch: "❌ Cảnh báo sai phác đồ: Đất đang bị chua hóa, cần xử lý rải vôi bột (CaCO3) và bón vi sinh thay vì tiêu úng.",
    toastTriggerSuccess: "🎉 Kích hoạt thành công! Hệ thống đang giải cứu cây và khôi phục các chỉ số về vùng tối ưu...",
    toastTriggerError: "Lỗi gửi lệnh kích hoạt. Vui lòng kiểm tra lại kết nối thiết bị.",
    toastRemoteMobile: "📱 Lệnh từ điện thoại: Đã kích hoạt",

    // Batch Scanner
    batchBadgeEngine: "Big Data High-Throughput Engine",
    batchBadgeMaxRows: "Hỗ Trợ Tối Đa 500,000 Dòng",
    batchTitle: "Xử Lý Dữ Liệu Lớn Theo Lô & Đua Hiệu Năng 2 Bộ Não",
    batchDesc: "Quét song song hàng trăm ngàn dòng dữ liệu cảm biến IoT: So sánh trực diện cơ chế Single-Node (LightGBM) và 6 Partitions phân tán (Apache Spark MLlib).",
    btnMetadataSpec: "Đặc Tả Siêu Dữ Liệu 17 Cột (TXT)",
    btnLoad200k: "Nạp Nhanh Tập 200,000 Dòng Có Sẵn",
    btnDownloadSample: "Tải File CSV Mẫu (100 dòng)",
    dropzoneText: "Kéo thả hoặc bấm vào đây để tải lên tệp CSV cảm biến",
    dropzoneSubtext: "Hỗ trợ tệp định dạng .csv từ 100 đến 500,000 dòng (Bao gồm tệp 200,000 dòng của bài toán)",
    dropzoneSelected: "Đã chọn:",
    engineSelectLabel: "Chế độ quét:",
    engineDual: "⚔️ Đua Hiệu Năng 2 Bộ Não (Dual Arena)",
    engineLightGBM: "⚡ LightGBM Engine (Single-Node)",
    engineSpark: "🔥 Apache Spark MLlib (6 Partitions)",
    modelSourceLabel: "Nguồn Trọng Số Mô Hình:",
    btnUploadScan: "Bắt Đầu Quét Tệp Đã Chọn",
    btnScanning: "Đang Quét Dữ Liệu Lô...",
    batchLoadingTitle: "Hệ Thống Đang Xử Lý Vector Hóa & Đua Hiệu Năng 2 Bộ Não...",
    batchLoadingSubtitle: "Đang phân luồng dữ liệu vào C++ Monolithic RAM và 6 Partitions Apache Spark MLlib",
    batchViewModeLabel: "Chế độ hiển thị:",
    batchDualArenaTag: "⚔️ Đối Chiếu Song Song (Dual Arena)",
    batchSingleLgbTag: "⚡ Quét Đơn Lẻ: LightGBM (1 Partition)",
    batchSingleSparkTag: "🔥 Quét Đơn Lẻ: Apache Spark MLlib (6 Partitions)",
    batchViewDualBtn: "⚔️ Đua Hiệu Năng Song Song",
    batchViewLgbBtn: "⚡ Chỉ Xem Đơn Lẻ LightGBM",
    batchViewSparkBtn: "🔥 Chỉ Xem Đơn Lẻ Spark MLlib",
    batchTotalRecords: "TỔNG SỐ BẢN GHI",
    batchEngineExec: "BỘ NÃO THỰC THI",
    batchExecTime: "THỜI GIAN THỰC THI",
    batchSparkTime: "THỜI GIAN PHÂN TÁN",
    batchLgbTime: "THỜI GIAN LIGHTGBM",
    batchStressTrees: "CÂY GẶP STRESS SINH THÁI",
    batchSliceNavTitle: "Khảo Sát Phân Đoạn Dữ Liệu Bất Kỳ (Tối đa 25 dòng / lượt):",
    batchShowingRows: "Đang hiển thị từ dòng",
    batchJumpQuick: "Nhảy nhanh:",
    fromRowLabel: "Từ dòng:",
    toRowLabel: "Đến dòng:",
    btnApplySlice: "Xem Phân Đoạn Này",
    batchLoadingSlice: "Đang nạp phân đoạn...",
    batchSliceMaxLimit: "(Nhập ít hơn 25 dòng được chấp nhận, tối đa không quá 25 dòng)",
    batchTableTitle: "Bảng Dữ Liệu Cảm Biến Toàn Diện",
    batchTableSubtitle: "Hiển thị đầy đủ tất cả 17 trường dữ liệu từ tệp CSV gốc (chuẩn theo đặc tả 1_plants_environment_dataset.txt) cùng 4 trường chẩn đoán và đối chứng của AI",
    batchGrpDevices: "🛰️ Thiết Bị & Thực Địa (6 Cột)",
    batchGrpSoil: "🌱 Đất & Khí Hậu IoT (8 Cột)",
    batchGrpSeason: "🌾 Sinh Thái & Mùa Vụ (2 Cột)",
    batchGrpTarget: "🎯 Nhãn Gốc & AI (5 Cột)",
    batchThRecordId: "Mã Bản Ghi",
    batchThSensorId: "Mã Cảm Biến",
    batchThImage: "Ảnh Thực Địa",
    batchThNote: "Ghi Chú",
    batchThTag: "Thẻ ID",
    batchThBattery: "Pin (%)",
    batchThSoilPh: "Độ pH Đất",
    batchThMoisture: "Độ Ẩm Đất (%)",
    batchThTemp: "Nhiệt Độ (°C)",
    batchThSunlight: "Nắng (h/ngày)",
    batchThPollution: "Chỉ Số Ô Nhiễm",
    batchThProximity: "Cách Nước (m)",
    batchThElevation: "Độ Cao (m)",
    batchThVegDensity: "Mật Độ Cây",
    batchThSeason: "Mùa Vụ",
    batchThSpecies: "Loài Thực Vật",
    batchThActualLabel: "Nhãn Gốc CSV",
    batchThStressProb: "Xác Suất Stress",
    batchThAiDiagnosis: "Chẩn Đoán AI",
    batchThRiskLevel: "Mức Độ Nguy Cơ",
    batchThVerification: "Kiểm Chứng",
    batchMatched: "✓ Khớp 100%",
    batchMismatch: "⚠ Độ lệch",
    batchNewInference: "Suy luận mới",
    batchHealthy: "Khỏe Mạnh",
    batchUnhealthy: "Nguy Cơ Stress",
    batchUnlabeled: "Chưa dán nhãn",
    batchRecentAudit: "Nhật Ký Các Lô Big Data Đã Quét Gần Đây (PostgreSQL Audit Log)",
    batchThJobId: "Mã Job",
    batchThFileName: "Tên Tệp",
    batchThRecords: "Số Bản Ghi",
    batchThStressed: "Cây Stress",
    batchThOptimal: "Cây Khỏe",
    batchThDuration: "Thời Gian Xử Lý",
    batchThTimestamp: "Thời Điểm Quét",
    recentJobsTitle: "Nhật Ký Các Lô Big Data Đã Quét Gần Đây",
    noJobsYet: "Chưa có đợt quét nào được ghi nhận.",
    schemaModalTitle: "Đặc Tả Cấu Trúc Dữ Liệu Lô (17 Thuộc Tính Chuẩn Thổ Nhưỡng)",

    // Academic Hub
    academicDefenseBadge: "HUIT Big Data Defense Ready",
    academicRecordsCount: "200,000 Bản Ghi Cảm Biến",
    academicTitle: "Trung Tâm Báo Cáo Đối Chứng Học Thuật & Xử Lý Phân Tán",
    academicSubtitle: "Đề tài Nông nghiệp Thông minh: Đối chiếu Thư viện Thông thường (LightGBM) vs Apache Spark MLlib (6 Partitions)",
    academicBtnDownloadLgb: "Tải Artifacts LightGBM (.ZIP)",
    academicBtnDownloadSpark: "Tải Artifacts Spark MLlib (.ZIP)",
    subTabSparkVsTrad: "ĐỐI CHỨNG: THƯ VIỆN THƯỜNG VS APACHE SPARK MLLIB (TRỌNG TÂM BIG DATA)",
    subTabTrack1VsTrack2: "ĐỐI CHỨNG BÀI TOÁN: TRACK 1 (DỮ LIỆU GỐC) VS TRACK 2 (ECO-STRESS SOTA)",
    academicStatTradLib: "THƯ VIỆN THÔNG THƯỜNG",
    academicStatRealtimeServing: "Realtime Serving",
    academicStatTrainTime: "Thời gian train",
    academicStatSparkTitle: "APACHE SPARK MLLIB",
    academicStatSparkBadge: "6 Partitions RDD",
    academicStatMathParity: "ĐỐI CHIẾU TOÁN HỌC",
    academicStatMathBadge: "Chuẩn 100%",
    academicStatMathTitle: "Toàn Vẹn Độ Chính Xác",
    academicStatOverhead: "BẢN CHẤT BIG DATA",
    academicStatOverheadBadge: "Distributed Cost",
    academicStatOverheadTitle: "Distributed Overhead",
    academicStatRows: "Dòng (~23.5 MB)",
    academicTableTitle: "Bảng Đối Chứng Thực Nghiệm: Thư Viện Thông Thường vs Apache Spark MLlib",
    academicTableSubtitle: "Trích xuất trực tiếp từ kết quả chạy thực tế trên Kaggle (Tập dữ liệu 200,000 dòng cảm biến)",
    academicTableArchitecturesBadge: "7 Kiến Trúc Đã Đánh Giá",
    viewSideBySide: "👥 So Sánh Song Song 2 Bên (Khuyên Dùng)",
    viewSparkOnly: "🔥 6 Biểu Đồ Spark MLlib",
    viewTradOnly: "⚡ 6 Biểu Đồ Thư Viện Thường",
    academicGalleryTitle: "Thư Viện Đối Chứng Biểu Đồ Khoa Học (300 DPI)",
    academicGalleryBadge: "Đồng Bộ 6x6 Chuẩn Đối Ứng",
    academicGallerySubtitle: "Đặt cạnh nhau để so sánh trực diện từng tiêu chí giữa Thư viện thông thường (LightGBM) và Apache Spark MLlib",
    academicSideBySideBadge: "Đối Chiếu Song Song Trực Diện",
    academicTradSubhead: "THƯ VIỆN THƯỜNG (LIGHTGBM)",
    academicSparkSubhead: "APACHE SPARK MLLIB",
    academicZoom: "Phóng to",
    academicDownloadPng: "Tải ảnh PNG",
    academicInsight: "Nhận xét đối chứng học thuật:",
    academicZoomDownload300: "Tải ảnh 300 DPI",
    academicColModel: "Mô Hình Huấn Luyện",
    academicColEngine: "Nền Tảng Thực Thi",
    academicColEnv: "Môi Trường Thực Thi",
    academicColPartitions: "Phân Vùng (Partitions)",
    academicColTrainTime: "Thời Gian Train",
    academicColAccuracy: "Accuracy",
    academicColPrecision: "Precision",
    academicColRecall: "Recall",
    academicColF1: "F1-Score",
    academicColRocAuc: "ROC-AUC",
    academicColRole: "Đặc Tính Ứng Dụng",
    badgeSotaRealtime: "SOTA Phục Vụ Realtime Web/Mobile",
    badgeSparkBest: "Mô Hình Phân Tán Tốt Nhất",
    badgeEnsemble: "Ensemble Phân Tán",
    badgeDecisionTree: "Cây Quyết Định Phân Tán",
    // Batch Scanner Extra
    batchSingleLgbDesc: "Khởi chạy suy luận trực tiếp trên cấu trúc mảng bộ nhớ RAM đơn luồng (Monolithic Memory) với thuật toán Gradient Boosting tối ưu",
    batchSingleLgb1Part: "1 Partition (Single-Node)",
    batchSpecsAndThroughput: "⚡ Thông Số & Tốc Độ Xử Lý",
    batchMemArch: "Kiến trúc bộ nhớ:",
    batchPartitionsCount: "Số lượng phân vùng:",
    batchContiguousRam: "Khối mảng RAM liền kề",
    batchExecutionTime: "Thời gian thực thi:",
    batchSeconds: "giây",
    batchProcessingSpeed: "Tốc độ xử lý:",
    batchRecordsSec: "bản ghi / giây",
    batchRamUsage: "Mức ngốn RAM:",
    batchExtremelyLight: "Cực kỳ tiết kiệm",
    batchSingleThreadProgress: "Tiến trình quét đơn luồng:",
    batchRowsUnit: "dòng",
    batchCppSpecsAndLimits: "🔬 Đặc Điểm Kỹ Thuật & Giới Hạn C++",
    batchLightgbmFastReason: "LightGBM đạt tốc độ suy luận nhanh đột biến trên tập 200,000 dòng nhờ vào cấu trúc Histogram-based Binning và cơ chế Leaf-wise Tree Growth, cho phép duyệt các nút nhánh cây nhị phân trực tiếp trên CPU Cache L1/L2/L3 mà không phải chịu chi phí khởi tạo JVM hay đóng gói dữ liệu mạng (Network Overhead).",
    batchPhysicalLimitReport: "⚠️ Giới hạn vật lý cần báo cáo: ",
    batchPhysicalLimit: "⚠️ Giới hạn vật lý: ",
    batchSingleSparkTitle: "Kết Quả Quét Lô Đơn Lẻ: Apache Spark MLlib (Distributed RDD)",
    batchSingleSparkSubtitle: "Dữ liệu 200,000 dòng được phân rã thành 6 phân vùng RDD song song, xử lý qua 4 DAG stages trên các Worker độc lập",
    batch6PartitionsDist: "6 Partitions Phân Tán",
    batchClusterSpecsAnd6Workers: "🔥 Thông Số Cụm & 6 Partitions Worker",
    batchDistArch: "Kiến trúc phân tán:",
    batch6WorkerThreadsParallel: "6 luồng Worker song song",
    batchSubjectToOverhead: "chịu Distributed Overhead",
    batchViaJvmPy4j: "qua JVM Py4J",
    batchRamJvmHeap: "Mức ngốn RAM / JVM Heap:",
    batchJvmHeapRddCache: "JVM Heap & RDD Cache",
    batch6WorkersParallelProgress: "Tiến trình 6 Worker song song trên từng Partition:",
    batchDagPipelineStages: "⚡ Chu Kỳ Thực Thi 4 DAG Pipeline Stages",
    batchVitalAdvantage: "🏆 Ưu thế Big Data sống còn: ",
    batchBigDataPower: "🏆 Sức mạnh Big Data: ",
    batchDualArenaHeader: "Đấu Trường Hiệu Năng 2 Bộ Não: LightGBM vs Apache Spark MLlib",
    batchDualArenaSub: "Đối chiếu trực diện cơ chế phân bổ bộ nhớ RAM, cấu trúc luồng và khả năng mở rộng quy mô Big Data",
    batchSideBySideBadge: "Đối Chiếu Song Song",
    batchBrain1Title: "BỘ NÃO 1: LIGHTGBM CLASSIFIER",
    batchBrain2Title: "BỘ NÃO 2: APACHE SPARK MLLIB",
    batchJuryConclusionTitle: "Kết Luận Đối Chứng Kỹ Thuật Cho Hội Đồng: ",
    batchJuryConclusionText: "Cả hai bộ não đều cho kết quả phân loại đồng nhất (phát hiện chính xác số lượng cây stress). Ở tập dữ liệu 200,000 dòng (~23.5MB), LightGBM nhanh hơn nhờ vào tính toán mảng C++ trực tiếp trên RAM. Tuy nhiên, khi tập dữ liệu mở rộng lên hàng chục Gigabyte từ hàng ngàn cảm biến gửi về mỗi ngày, Apache Spark MLlib là lựa chọn sống còn duy nhất vì có khả năng phân tán dữ liệu ra nhiều máy Worker mà không bao giờ bị lỗi tràn bộ nhớ (Out-Of-Memory).",
    batchFullVerificationTitle: "Báo Cáo Kiểm Chứng Đối Chiếu Toàn Bộ",
    batchFullVerificationSuffix: "Bản Ghi (Big Data Full-Scan)",
    batchFullMatchRate: "Tỷ Lệ Khớp Toàn Tập:",
    batchMatchedCardTitle: "✓ KHỚP CHUẨN (MATCHED)",
    batchMatchedCardDesc: "toàn bộ tập dữ liệu",
    batchEarlyWarningCardTitle: "⚠ CẢNH BÁO SỚM IOT (EARLY WARNING)",
    batchEarlyWarningCardDesc: "Đất kiệt nước, AI báo động trước khi cây héo rũ",
    batchFieldNoiseCardTitle: "🔍 NHIỄU THỰC ĐỊA / SÂU BỆNH ẨN",
    batchFieldNoiseCardDesc: "Mẫu ghi chú noisy/suspect theo đặc tả TXT",
    batchDeviationExplTitle: "Giải Thích Kỹ Thuật Cho Hội Đồng Về \"⚠ Độ Lệch\" & Kiến Trúc Hiển Thị Big Data:",
    batchDeviationExplText1: "Vì sao dòng #3 (record_id 117949) bị gắn nhãn \"⚠ Độ lệch\"? Cảm biến thực tế ghi nhận độ ẩm đất cực thấp 7.87%, nhiệt độ 32.6°C, cách nguồn nước 880m (chỉ số hạn hán cực đoan). AI phát hiện rễ cây đang kiệt nước nghiêm trọng và phát tín hiệu Cảnh Báo Sớm để kích hoạt van tưới tự động cứu cây. Nhãn CSV ghi \"Healthy\" do độ trễ sinh học thực địa (khi đi đo lá cây chưa kịp ngả vàng). Đây là giá trị đắt giá nhất của IoT AI!",
    batchDeviationExplText2: "Có nên load toàn bộ 200,000 dòng lên giao diện web không? Tuyệt đối không! 200,000 dòng × 21 cột = 4,200,000 thẻ HTML DOM sẽ ngốn >3GB RAM và làm sập trình duyệt ngay lập tức (Aw, Snap! Out of Memory). Chuẩn công nghiệp Big Data (Apache Spark df.show(20), BigQuery, Databricks) luôn xử lý 100% dữ liệu trong RAM backend, chỉ hiển thị chỉ số tổng hợp và cửa sổ preview mẫu 25 dòng.",
    batchWeightSourceActiveLabel: "Nguồn Trọng Số Đang Áp Dụng:",
    batchWeightSparkSub: "Ngưỡng quyết định chuẩn T* = 0.50 | 30 cây GBDT phân tán độc lập | Biên độ xác suất sắc nét (1.39% - 96.65%)",
    batchWeightLgbSub: "Ngưỡng cắt tối ưu ROC T* = 0.35 | Hệ số phạt mất cân bằng scale_pos_weight = 6.24 | Cực trị bimodal (18.6% - 54.0%)",
    batchBtnUseLgbWeights: "🟢 Dùng Trọng Số LightGBM",
    batchBtnUseSparkWeights: "🔥 Dùng Trọng Số Apache Spark",
    batchSelectedTag: "Đang chọn",
    batchSparkEmpiricalDiffTitle: "💡 Khác biệt thực nghiệm của Apache Spark MLlib: ",
    batchSparkEmpiricalDiffText: "Mô hình GBTClassifier phân tán của Spark sử dụng 30 cây quyết định không áp hệ số ép mẫu mất cân bằng. Nhờ đó, xác suất phản ánh trung thực toàn dải 0% - 100%: Cây khỏe bình thường giảm sâu chỉ còn ~1.39% nguy cơ, trong khi cây hạn hán kiệt nước (như dòng #3, độ ẩm đất 7.87%) vọt thẳng lên 96.65%! Hãy quan sát cột \"Xác Suất Stress\" bên dưới bảng.",
    batchLgbEmpiricalDiffTitle: "💡 Khác biệt thực nghiệm của LightGBM SOTA: ",
    batchLgbEmpiricalDiffText: "Do tập dữ liệu có đến 97% cây khỏe và 3% cây bệnh, mô hình LightGBM sử dụng hệ số phạt scale_pos_weight = 6.24 để ưu tiên bảo vệ nông sản. Toàn bộ xác suất logit bị nén ở 2 cụm giá trị: Cây khỏe hội tụ quanh ~18.6% và cây rủi ro tiệm cận trần ~54.0% (với ngưỡng phân định tối ưu ROC T* = 35.0%). Hãy bấm nút [🔥 Dùng Trọng Số Apache Spark] phía trên để xem sự khác biệt!",

    // Mobile QR & SQLite History Extra
    qrGenerating: "Đang tạo mã QR...",
    dbNoRecords: "Chưa có bản ghi thực địa nào được lưu.",
    actuatorAuditTitle: "Nhật Ký Thiết Bị Cứu Cây Đã Được Kích Hoạt (Actuator Audit Logs)",
    actuatorAuditSubtitle: "Bảng actuator_logs trong SQLite — Ghi nhận kiểm toán mọi lệnh kích hoạt thiết bị",
    thCmdId: "Mã Lệnh",
    thDeviceName: "Tên Thiết Bị",
    thCmdType: "Loại Lệnh",
    thDuration: "Thời Lượng",
    thTriggeredBy: "Người Kích Hoạt",
    thStatus: "Trạng Thái",
    noActuatorsYet: "Chưa có thiết bị nào được kích hoạt.",
    statusSuccess: "Thành Công",

    // Academic Hub Extra
    academicTradInferenceNote: "• Phản hồi suy luận: < 20ms trên Web & Mobile",
    academicTradArchNote: "• Kiến trúc: Single-Node C++ biên dịch tối ưu",
    academicSparkStructNote: "• Cấu trúc: 6 RDD Partitions (local[*])",
    academicSparkExecNote: "• Thực thi: DAG Stages song song qua JVM",
    academicMathFidelityNote: "• Thuật toán phân tán không làm giảm chất lượng",
    academicMathBaselineNote: "• Cả 2 đều vượt trội hoàn toàn so với Baseline (0.50)",
    academicMathF1Note: "• F1-Score đạt 0.78 - 0.94 cực kỳ ổn định",
    academicOverheadRamNote: "• Dữ liệu < RAM: Single-node C++ thắng vì nhẹ",
    academicOverheadOomNote: "• Dữ liệu > RAM (Big Data): Sklearn sập OOM",
    academicOverheadScaleNote: "• Spark mở rộng ngang (Scale-out) trên cụm máy",
    academicAnalysis1Title: "Giải Mã Chi Phí Phân Tán (Distributed Overhead)",
    academicAnalysis1P1: "Tại sao LightGBM chỉ mất 1.25s còn Spark mất 21.4s?",
    academicAnalysis1P2: "Tập dữ liệu 200,000 dòng có dung lượng ~23.5 MB, hoàn toàn nằm gọn trong RAM. Ở quy mô này, thư viện C++ (LightGBM) không tốn bất kỳ chi phí mạng hay phân mảnh bộ nhớ nào.",
    academicAnalysis1P3: "Trong khi đó, Apache Spark MLlib phải: 1) Khởi động máy ảo Java (JVM); 2) Tuần tự hóa dữ liệu qua Py4J Gateway; 3) Băm dữ liệu vào 6 Partitions và lập lịch đồ thị DAG. Chi phí quản lý phân tán này lớn hơn thời gian tính toán thực tế.",
    academicAnalysis2Title: "Khi Nào Apache Spark MLlib Bất Khả Chiến Bại?",
    academicAnalysis2P1: "Vấn đề Out-Of-Memory (OOM) của máy đơn:",
    academicAnalysis2P2: "Khi nông trường tích lũy dữ liệu nhiều năm lên đến 50GB hoặc 500GB, việc nạp vào Pandas hoặc Scikit-Learn trên laptop sẽ lập tức gây sập phần mềm vì tràn RAM.",
    academicAnalysis2P3: "Khả năng mở rộng ngang (Scale-out):",
    academicAnalysis2P4: "Apache Spark MLlib không bị giới hạn bởi RAM của 1 máy. Khi dữ liệu tăng gấp 10 lần, ta chỉ cần thêm Worker Nodes vào cụm Cluster để dữ liệu tự động chia đều qua các Partitions mà không cần sửa một dòng code nào.",
    academicAnalysis3Title: "Kiến Trúc Chuẩn Kết Hợp: Lambda Architecture",
    academicAnalysis3P1: "Tầng Xử lý Lô (Batch Layer - Spark MLlib):",
    academicAnalysis3P2: "Chạy định kỳ vào ban đêm trên cụm Hadoop / Databricks để phân tích dữ liệu lớn lịch sử, tái huấn luyện mô hình và cập nhật trọng số.",
    academicAnalysis3P3: "Tầng Phục vụ Thời gian thực (Speed Layer - LightGBM Serving):",
    academicAnalysis3P4: "Nhúng mô hình tối ưu vào Web Server FastAPI để phục vụ người dùng gạt thanh trượt cảm biến phản hồi dưới 20ms trên Web và Mobile.",
    academicTrack1Badge: "Track 1: Dữ Liệu Gốc Của Thầy",
    academicTrack1Title: "Nghịch Lý Độ Chính Xác 97% (The 97% Accuracy Paradox)",
    academicTrack1P1: "Mô hình Dummy đạt 96.91% Accuracy chỉ bằng cách đoán tất cả cây đều khỏe mạnh. Nhưng Recall và F1-Score đều bằng 0.",
    academicTrack1P2: "Kiểm định thống kê chứng minh nhãn plant_health phân bố ngẫu nhiên độc lập với 9 biến môi trường (Zero-Signal). Mọi thuật toán AI đều dừng ở sàn ngẫu nhiên ROC-AUC = 0.50.",
    academicTrack2Badge: "Track 2: Nhãn Sinh Thái Chuẩn (SOTA)",
    academicTrack2DeployBadge: "Đưa Vào Ứng Dụng Web",
    academicTrack2Title: "Mô Hình LightGBM Tối Ưu Ngưỡng Quyết Định T* = 0.34",
    academicTrack2P1: "Bổ sung 4 đặc trưng sinh thái nông học (Axit hóa, Sốc nhiệt/hạn, Thủy văn, Ô nhiễm).",
    academicTrack2P2: "Mô hình hội tụ hoàn hảo sau 150 vòng lặp, đạt ROC-AUC 0.83, Precision 95.05% và F1-Score 0.778.",
    academicTrack2P3: "Đây là mô hình lõi đang vận hành trên Web Command Center & Mobile PWA.",
    academicRenderingChart: "📊 Biểu đồ đang được kết xuất...",

    // Mobile QR Sync & Standalone Mobile View
    mobileSyncTitle: "Trạm Thực Địa Di Động & Đồng Bộ Hai Chiều Realtime (QR Code)",
    mobileSyncDesc: "Quét mã QR bằng camera điện thoại thông minh để đồng bộ cảm biến thực địa và điều khiển thiết bị cứu cây trực tiếp qua WebSocket.",
    mobileWsReady: "WebSocket Sẵn Sàng (<50ms)",
    mobileWsWaiting: "Đang Chờ Kết Nối",
    btnRecreateQR: "Tạo Lại Mã QR",
    serverStatusRest: "REST API Máy Chủ:",
    serverStatusDb: "Cơ Sở Dữ Liệu:",
    serverStatusWs: "Đường Truyền Hub:",
    qrSessionId: "Mã phiên duy nhất (Giữ nguyên ổn định khi đổi tab)",
    qrLanIpLabel: "📡 Địa chỉ IP LAN Máy Chủ (để điện thoại quét vào):",
    btnOpenMobilePreview: "Mở Xem Thử Giao Diện Mobile",
    wsLiveLogTitle: "Nhật Ký Tín Hiệu WebSocket Thời Gian Thực",
    wsLatencyTip: "Độ trễ < 50ms",
    mobileSimTitle: "Bấm Nhanh Mô Phỏng Điện Thoại Gửi Dữ Liệu:",
    simFloodBtn: "🌊 Gửi Ngập Úng (92%)",
    simDroughtBtn: "☀️ Gửi Hạn Hán (18%, 38°C)",
    simAcidBtn: "🍋 Gửi Đất Chua (pH 4.2)",
    simOptimalBtn: "🌱 Gửi Tối Ưu (pH 6.6, Ẩm 65%)",
    wsLogListening: "Đang lắng nghe kết nối từ điện thoại di động...",
    dbHistoryTitle: "Nhật Ký Đo Đạc Thực Địa & Chẩn Đoán Lưu Trong Cơ Sở Dữ Liệu SQLite",
    dbHistorySubtitle: "Bảng sensor_diagnostics trong SQLite (Tự động cập nhật tức thì khi Mobile gửi dữ liệu)",
    btnReloadTable: "Tải Lại Bảng",
    btnExportCsv: "Xuất CSV",
    thId: "ID (DB)",
    thTime: "Thời Gian",
    thSource: "Nguồn Dữ Liệu",
    thPh: "pH",
    thMoisture: "Độ Ẩm",
    thTemp: "Nhiệt Độ",
    thStressProb: "Xác Suất Stress",
    thRiskLevel: "Mức Rủi Ro",
    thRemediation: "Phác Đồ Điều Trị",

    // Mobile Standalone View
    mobileHeaderTitle: "Trạm Đo Thực Địa Nông Hộ",
    mobileHeaderSubtitle: "Đồng bộ tức thì với Trạm Trung Tâm",
    mobileBackToWeb: "← Quay Lại Bảng Điều Khiển Web",
    mobileSyncToServerBtn: "Đồng Bộ Lên Hệ Thống Trung Tâm",
    mobileSyncingBtn: "Đang Đồng Bộ...",

    // Chatbot
    chatTitle: "AgriBot AI — Bác Sĩ Cây Trồng",
    chatExpandedTip: "Chế độ cửa sổ mở rộng toàn màn hình • Nhớ ngữ cảnh hội thoại đa lượt",
    chatStandardTip: "Nhớ ngữ cảnh hội thoại đa lượt",
    chatApiKeyButton: "Nhập Key",
    chatApiKeySaved: "API Key Đã Nạp",
    chatApiKeyConfigTitle: "Cấu hình Google Gemini API Key",
    chatApiKeySaveBtn: "Lưu Key",
    chatApiKeySavedToast: "Đã lưu key vào bộ nhớ trình duyệt!",
    chatModelSelectLabel: "Mô hình AI:",
    chatModelGemini: "Google Gemini Flash (Online Kết Nối Trực Tiếp)",
    chatModelInternal: "Tri Thức Nông Học Nội Bộ (Offline Không Cần Mạng)",
    chatPlaceholder: "Nhập câu hỏi về cây trồng, đất, vi khí hậu, sâu bệnh...",
    chatSend: "Gửi",
    chatWelcome: "Xin chào! Tôi là AgriBot — Bác sĩ Cây trồng & Trợ lý Nông học Thông minh của hệ thống AgriGuard-IoT 🌿.\n\nBạn có thể hỏi tôi bất kỳ câu hỏi nào về đất chua, ngập úng, hạn hán, mất cân đối NPK, hay sâu bệnh hại cây trồng!",
    chatNewSession: "Cuộc trò chuyện mới đã bắt đầu! Mời bạn đặt câu hỏi về cây trồng và vi khí hậu nông nghiệp 🌱",
    chatPrompt1: "Đất đang bị ngập úng 92% thì xử lý thế nào?",
    chatPrompt2: "Đất chua pH 4.2 bón bao nhiêu vôi bột?",
    chatPrompt3: "Nhiệt độ 39°C có nên tưới đẫm nước giữa trưa không?",
    chatThinking: "🌿 AgriBot đang tham vấn Google Gemini và phân tích phác đồ nông học...",
    btnMaximize: "Phóng to cửa sổ chat để đọc đầy đủ",
    btnMinimize: "Thu nhỏ lại cửa sổ chuẩn",
    btnRefreshChat: "Xóa làm mới cuộc hội thoại",
    btnCloseChat: "Đóng chat",
  },

  en: {
    // Navbar
    brandTitle: "AgriGuard-IoT",
    brandSubtitle: "Smart Agro-Ecological Decision Support System",
    tabDashboard: "Real-Time Dashboard",
    tabBatch: "Big Data Batch Scan",
    tabAcademic: "Academic Dual-Track Hub",
    tabMobile: "Mobile Field Station (QR)",
    btnDemoLogin: "Quick Demo Login",
    demoMenuTitle: "1-Click Demo by Role",
    btnLogout: "Sign Out",
    roleAdmin: "Admin",
    roleEngineer: "Agronomy Engineer",
    roleFarmer: "Farmer",
    roleGuest: "Guest",
    authSignInRegister: "Sign In / Register",
    authSignIn: "Sign In",
    authRegister: "Create Account",
    switchThemeTitle: "Toggle Dark / Light Theme",
    switchLangTitle: "Switch Language / Đổi Ngôn Ngữ",

    // Auth Modal
    authModalTitleLogin: "System Sign In",
    authModalTitleRegister: "Create New Account",
    authModalSubtitle: "Role-based access control: Admin, Agronomy Engineer, or Farmer",
    authEmailLabel: "Email Address",
    authPasswordLabel: "Password",
    authFullNameLabel: "Full Name",
    authRoleLabel: "System Role",
    authBtnLogin: "Sign In",
    authBtnRegister: "Register",
    authNoAccount: "Don't have an account?",
    authHaveAccount: "Already have an account?",
    authSwitchToRegister: "Register now",
    authSwitchToLogin: "Sign in now",
    authDemoTitle: "Or 1-click quick demo login (For Reviewers / Jury):",
    authLoginSuccess: "Signed in successfully!",
    authRegisterSuccess: "Account created! Signing in automatically...",

    // Dashboard Hero & Gauge
    heroTitle: "Real-Time Plant Eco-Stress Monitoring & Diagnostics",
    heroDesc: "Fusing 9 environmental sensor streams, LightGBM inference at optimal T*=0.34 threshold, and instant prescriptive agronomic protocols.",
    riskGaugeTitle: "Eco-Stress Risk Gauge",
    statusOptimal: "OPTIMAL GROWTH",
    statusWarning: "EARLY WARNING DEGRADATION",
    statusCritical: "CRITICAL ALERT — INTERVENE NOW!",
    statusOptimalDesc: "All metrics within safe ecological bounds",
    statusWarningDesc: "Eco-system degrading, close monitoring required",
    statusCriticalDesc: "Critical threshold! Root or cellular damage imminent",
    stressProbLabel: "Predicted Stress Probability",
    execTimeLabel: "AI Inference Latency",
    gaugeDetailsBtn: "Details",
    gaugeLatencyExpl: "Represents end-to-end Python Backend computing latency: ingesting 9 sensor streams, computing 4 agro-ecological indices, and running inference matrix.",
    gaugeModelExplTitle: "Model Distinction:",
    gaugeModelExplLgb: "Continuously calibrated on Eco-Stress validation set, delivering fine probability resolution (18% - 54%).",
    gaugeModelExplSpark: "Distributed training across 6 Partitions with Log-loss optimization, highly polarized (1.4% - 96.6%).",

    // Sliders
    slidersTitle: "9 Eco-Field Sensor Channels",
    slidersDesc: "Slide to simulate micro-climate variance or select sample presets.",
    slidersReadOnly: "Read-Only (Farmer Role)",
    presetOptimal: "🌱 Optimal",
    presetAcidic: "🍋 Acidic Soil",
    presetHeatwave: "🔥 Heat & Drought",
    presetFlood: "🌊 Waterlogged",
    soilPh: "Soil pH Level",
    soilMoisture: "Soil Moisture",
    airTemp: "Air Temperature",
    sunlight: "Sunlight Hours",
    pollution: "Pollution Index",
    vegDensity: "Vegetation Density",
    proximityWater: "Proximity to Water",
    elevation: "Terrain Elevation",
    season: "Season",
    plantSpecies: "Plant Species",
    unitHoursPerDay: "hrs/day",
    outOfBoundsWarning: "⚠️ Out of safe bounds",
    bioOptimalSafe: "Bio-optimal",
    seasonSpring: "🌸 Spring",
    seasonSummer: "☀️ Summer",
    seasonAutumn: "🍂 Autumn",
    seasonWinter: "❄️ Winter",
    cropRice: "🌾 Wet Rice (Wetland C)",
    cropFruit: "🍎 Fruit Trees (Tree Y)",
    cropVegetables: "🥦 Vegetables (Shrub X)",
    cropGrass: "🌿 Pasture Grass (Grassland B)",

    // Root Cause & Prescription
    rootCauseTitle: "Root-Cause Diagnosis & Prescriptive Protocol",
    rootCauseSubtitle: "Causal inference engine & immediate prescriptive agronomic protocols",
    rootCauseHeader: "Identified Ecological Stressors",
    remediationHeader: "Agronomic Treatment Plan",
    optimalStateCardTitle: "Optimal Growth State (0 Stressors Detected)",
    optimalStateCardDesc: "All biochemical metrics (soil pH, moisture) and micro-climate parameters are within safe ecological bounds. No adverse signs detected.",
    zeroCausesSafe: "0 Stressors (Safe)",
    causesDetectedSuffix: "Stressors Identified",
    actuatorsSectionTitle: "Direct Crop Rescue Actuators",
    actuatorsRoleReq: "Engineer / Admin Role Required",
    btnTriggerMisting: "Trigger Misting Sprayer",
    btnTriggerPump: "Trigger Irrigation Pump",
    btnTriggerDrainage: "Emergency Drainage Pump",
    btnTriggerAlert: "Trigger Audio Siren Alert",
    actuatorSending: "Sending command...",
    actuatorOpeningValve: "Opening valves...",
    actuatorBroadcasting: "Broadcasting...",
    toastOptimalWarn: "⚠️ Crops are in ideal optimal growth! Actuator intervention is unnecessary now (avoids resource waste and micro-climate disruption).",
    toastFloodMismatch: "❌ Prescription mismatch: Soil is severely waterlogged; pumping additional water will drown roots! Trigger 'Emergency Drainage Pump' instead.",
    toastDroughtMismatch: "❌ Prescription mismatch: Soil is suffering severe drought; drainage will deplete vital water! Trigger 'Irrigation Pump' or 'Misting Sprayer' instead.",
    toastAcidityMismatch: "❌ Prescription mismatch: Soil is heavily acidified; broadcast agricultural lime (CaCO3) and compost rather than drainage.",
    toastTriggerSuccess: "🎉 Actuator triggered successfully! System is rescuing crops and restoring metrics to optimal range...",
    toastTriggerError: "Failed to send actuator command. Please verify device connection.",
    toastRemoteMobile: "📱 Mobile remote command: Triggered",

    // Batch Scanner
    batchBadgeEngine: "Big Data High-Throughput Engine",
    batchBadgeMaxRows: "Supports Up To 500,000 Rows",
    batchTitle: "High-Throughput Batch Processing & Dual-Brain Benchmark",
    batchDesc: "Scan hundreds of thousands of IoT sensor rows concurrently: Direct comparison between Single-Node (LightGBM) and 6 Distributed Partitions (Apache Spark MLlib).",
    btnMetadataSpec: "17-Column Metadata Spec (TXT)",
    btnLoad200k: "Instant 200,000 Rows (Pre-loaded Demo)",
    btnDownloadSample: "Download Sample CSV (100 rows)",
    dropzoneText: "Drag & drop CSV dataset here or click to browse",
    dropzoneSubtext: "Supports ISO-standard .csv files with up to 500,000 records (Including project 200k benchmark set)",
    dropzoneSelected: "Selected file:",
    engineSelectLabel: "Scan Mode:",
    engineDual: "⚔️ Dual-Brain Benchmark Arena",
    engineLightGBM: "⚡ LightGBM Engine (Single-Node)",
    engineSpark: "🔥 Apache Spark MLlib (6 Partitions)",
    modelSourceLabel: "Model Weight Source:",
    btnUploadScan: "Execute Batch Diagnosis on File",
    btnScanning: "Scanning Big Data Records...",
    batchLoadingTitle: "System Vectorizing & Running Dual-Brain Benchmark...",
    batchLoadingSubtitle: "Streaming data into C++ Monolithic RAM and 6 Distributed Partitions of Apache Spark MLlib",
    batchViewModeLabel: "Display Mode:",
    batchDualArenaTag: "⚔️ Side-by-Side Dual Arena",
    batchSingleLgbTag: "⚡ Single Engine: LightGBM (1 Partition)",
    batchSingleSparkTag: "🔥 Single Engine: Apache Spark MLlib (6 Partitions)",
    batchViewDualBtn: "⚔️ Side-by-Side Dual Arena",
    batchViewLgbBtn: "⚡ View LightGBM Only",
    batchViewSparkBtn: "🔥 View Spark MLlib Only",
    batchTotalRecords: "TOTAL RECORDS",
    batchEngineExec: "EXECUTION ENGINE",
    batchExecTime: "EXECUTION TIME",
    batchSparkTime: "DISTRIBUTED LATENCY",
    batchLgbTime: "LIGHTGBM LATENCY",
    batchStressTrees: "PLANTS UNDER ECO-STRESS",
    batchSliceNavTitle: "Inspect Dynamic Data Slice (Max 25 rows per slice):",
    batchShowingRows: "Displaying rows",
    batchJumpQuick: "Quick jump:",
    fromRowLabel: "From row:",
    toRowLabel: "To row:",
    btnApplySlice: "Inspect This Slice",
    batchLoadingSlice: "Loading slice...",
    batchSliceMaxLimit: "(Up to 25 rows per slice supported)",
    batchTableTitle: "Comprehensive Sensor Telemetry Table",
    batchTableSubtitle: "Displaying all 17 raw features from original CSV alongside 4 AI diagnostic and verification attributes",
    batchGrpDevices: "🛰️ Devices & Field (6 Cols)",
    batchGrpSoil: "🌱 Soil & IoT Climate (8 Cols)",
    batchGrpSeason: "🌾 Ecology & Seasons (2 Cols)",
    batchGrpTarget: "🎯 Ground Truth & AI (5 Cols)",
    batchThRecordId: "Record ID",
    batchThSensorId: "Sensor ID",
    batchThImage: "Field Image",
    batchThNote: "Sample Note",
    batchThTag: "Random Tag",
    batchThBattery: "Battery (%)",
    batchThSoilPh: "Soil pH",
    batchThMoisture: "Moisture (%)",
    batchThTemp: "Temp (°C)",
    batchThSunlight: "Sunlight (h/d)",
    batchThPollution: "Pollution Idx",
    batchThProximity: "Water Dist (m)",
    batchThElevation: "Elevation (m)",
    batchThVegDensity: "Veg Density",
    batchThSeason: "Season",
    batchThSpecies: "Plant Species",
    batchThActualLabel: "CSV Ground Truth",
    batchThStressProb: "Stress Prob",
    batchThAiDiagnosis: "AI Diagnosis",
    batchThRiskLevel: "Risk Level",
    batchThVerification: "Verification",
    batchMatched: "✓ 100% Matched",
    batchMismatch: "⚠ Early Warning",
    batchNewInference: "New inference",
    batchHealthy: "Healthy",
    batchUnhealthy: "Stress Risk",
    batchUnlabeled: "Unlabeled",
    batchRecentAudit: "Recent Big Data Batch Scan Jobs (PostgreSQL Audit Log)",
    batchThJobId: "Job ID",
    batchThFileName: "Filename",
    batchThRecords: "Total Records",
    batchThStressed: "Stress Count",
    batchThOptimal: "Healthy Count",
    batchThDuration: "Execution Time",
    batchThTimestamp: "Timestamp",
    recentJobsTitle: "Recent Batch Scan Jobs",
    noJobsYet: "No batch scan history recorded yet.",
    schemaModalTitle: "Dataset Schema Specification (17 Standard Agronomic Features)",

    // Academic Hub
    academicDefenseBadge: "HUIT Big Data Defense Ready",
    academicRecordsCount: "200,000 Sensor Records",
    academicTitle: "Academic Dual-Track Hub & Machine Learning Benchmark",
    academicSubtitle: "Smart Agriculture Research: Rigorous empirical comparison between Single-Node Monolithic (LightGBM) and Distributed DAG Cluster (Apache Spark MLlib).",
    academicBtnDownloadLgb: "Download LightGBM Artifacts (.ZIP)",
    academicBtnDownloadSpark: "Download Spark MLlib Artifacts (.ZIP)",
    subTabSparkVsTrad: "BENCHMARK: CONVENTIONAL ML VS APACHE SPARK MLLIB (BIG DATA FOCUS)",
    subTabTrack1VsTrack2: "PROBLEM BENCHMARK: TRACK 1 (ORIGINAL DATA) VS TRACK 2 (ECO-STRESS SOTA)",
    academicStatTradLib: "CONVENTIONAL LIBRARY",
    academicStatRealtimeServing: "Realtime Serving",
    academicStatTrainTime: "Training time",
    academicStatSparkTitle: "APACHE SPARK MLLIB",
    academicStatSparkBadge: "6 Partitions RDD",
    academicStatMathParity: "MATHEMATICAL PARITY",
    academicStatMathBadge: "100% Validated",
    academicStatMathTitle: "Accuracy Integrity",
    academicStatOverhead: "BIG DATA CHARACTERISTICS",
    academicStatOverheadBadge: "Distributed Cost",
    academicStatOverheadTitle: "Distributed Overhead",
    academicStatRows: "Rows (~23.5 MB)",
    academicTableTitle: "Empirical Benchmark: Conventional Libraries vs Apache Spark MLlib",
    academicTableSubtitle: "Directly extracted from empirical evaluation on Kaggle (200,000 sensor dataset)",
    academicTableArchitecturesBadge: "7 Evaluated Architectures",
    viewSideBySide: "👥 Side-by-Side Dual View (Recommended)",
    viewSparkOnly: "🔥 6 Spark MLlib Charts",
    viewTradOnly: "⚡ 6 Conventional Charts",
    academicGalleryTitle: "Scientific Evaluation Chart Gallery (300 DPI)",
    academicGalleryBadge: "Synchronized 6x6 Benchmark",
    academicGallerySubtitle: "Side-by-side empirical comparison between Conventional (LightGBM) and Apache Spark MLlib",
    academicSideBySideBadge: "Direct Side-by-Side Comparison",
    academicTradSubhead: "CONVENTIONAL (LIGHTGBM)",
    academicSparkSubhead: "APACHE SPARK MLLIB",
    academicZoom: "Zoom in",
    academicDownloadPng: "Download PNG",
    academicInsight: "Academic comparative insight:",
    academicZoomDownload300: "Download 300 DPI Image",
    academicColModel: "Algorithm Model",
    academicColEngine: "Execution Engine",
    academicColEnv: "Execution Environment",
    academicColPartitions: "Partitions",
    academicColTrainTime: "Training Time",
    academicColAccuracy: "Accuracy",
    academicColPrecision: "Precision",
    academicColRecall: "Recall",
    academicColF1: "F1-Score",
    academicColRocAuc: "ROC-AUC",
    academicColRole: "Application Role",
    badgeSotaRealtime: "SOTA for Realtime Web/Mobile",
    badgeSparkBest: "Best Distributed Model",
    badgeEnsemble: "Distributed Ensemble",
    badgeDecisionTree: "Distributed Decision Tree",
    // Batch Scanner Extra
    batchSingleLgbDesc: "Direct inference on monolithic in-memory array RAM structure with optimized Gradient Boosting algorithm",
    batchSingleLgb1Part: "1 Partition (Single-Node)",
    batchSpecsAndThroughput: "⚡ Specifications & Processing Throughput",
    batchMemArch: "Memory Architecture:",
    batchPartitionsCount: "Partitions Count:",
    batchContiguousRam: "Contiguous In-Memory Array",
    batchExecutionTime: "Execution Time:",
    batchSeconds: "seconds",
    batchProcessingSpeed: "Processing Speed:",
    batchRecordsSec: "records / sec",
    batchRamUsage: "RAM Usage:",
    batchExtremelyLight: "Extremely lightweight",
    batchSingleThreadProgress: "Single-thread scanning progress:",
    batchRowsUnit: "rows",
    batchCppSpecsAndLimits: "🔬 Technical Characteristics & C++ Limits",
    batchLightgbmFastReason: "LightGBM achieves ultra-fast inference on the 200,000-row dataset via Histogram-based Binning and Leaf-wise Tree Growth, traversing binary tree splits directly on CPU L1/L2/L3 cache without JVM startup or network serialization overhead.",
    batchPhysicalLimitReport: "⚠️ Physical limitation to report: ",
    batchPhysicalLimit: "⚠️ Physical limitation: ",
    batchSingleSparkTitle: "Single Engine Batch Scan: Apache Spark MLlib (Distributed RDD)",
    batchSingleSparkSubtitle: "200,000 rows partitioned into 6 parallel RDD partitions, scheduled across 4 DAG stages on independent Workers",
    batch6PartitionsDist: "6 Distributed Partitions",
    batchClusterSpecsAnd6Workers: "🔥 Cluster Parameters & 6 Worker Partitions",
    batchDistArch: "Distributed Architecture:",
    batch6WorkerThreadsParallel: "6 Parallel Worker threads",
    batchSubjectToOverhead: "subject to Distributed Overhead",
    batchViaJvmPy4j: "via JVM Py4J",
    batchRamJvmHeap: "RAM / JVM Heap Usage:",
    batchJvmHeapRddCache: "JVM Heap & RDD Cache",
    batch6WorkersParallelProgress: "6 Parallel Workers progress across Partitions:",
    batchDagPipelineStages: "⚡ 4 DAG Pipeline Execution Stages",
    batchVitalAdvantage: "🏆 Vital Big Data advantage: ",
    batchBigDataPower: "🏆 Big Data scalability: ",
    batchDualArenaHeader: "Dual-Brain Performance Arena: LightGBM vs Apache Spark MLlib",
    batchDualArenaSub: "Direct empirical comparison of RAM allocation, threading architecture, and Big Data horizontal scalability",
    batchSideBySideBadge: "Side-by-Side Benchmark",
    batchBrain1Title: "BRAIN 1: LIGHTGBM CLASSIFIER",
    batchBrain2Title: "BRAIN 2: APACHE SPARK MLLIB",
    batchJuryConclusionTitle: "Technical Benchmark Conclusion for Committee: ",
    batchJuryConclusionText: "Both engines achieve identical classification results (accurately identifying plant stress cases). On the 200,000-row (~23.5MB) dataset, LightGBM executes faster due to direct monolithic C++ in-memory arrays. However, when scaling to tens of gigabytes streaming daily from thousands of IoT nodes, Apache Spark MLlib is the indispensable architecture as it distributes data across worker clusters without Out-Of-Memory (OOM) failures.",
    batchFullVerificationTitle: "Ground-Truth Verification Report for All",
    batchFullVerificationSuffix: "Records (Big Data Full-Scan)",
    batchFullMatchRate: "Full-Dataset Match Rate:",
    batchMatchedCardTitle: "✓ GROUND-TRUTH MATCHED",
    batchMatchedCardDesc: "of entire dataset",
    batchEarlyWarningCardTitle: "⚠ IOT EARLY WARNING",
    batchEarlyWarningCardDesc: "Moisture depleted, AI alarms before physical wilting",
    batchFieldNoiseCardTitle: "🔍 FIELD NOISE / HIDDEN PESTS",
    batchFieldNoiseCardDesc: "Samples with noisy/suspect notes per TXT specification",
    batchDeviationExplTitle: "Technical Clarification on \"⚠ Early Warning Deviation\" & Big Data Architecture:",
    batchDeviationExplText1: "Why is row #3 (record_id 117949) flagged as \"⚠ Early Warning\"? Field telemetry records critically low soil moisture at 7.87%, air temperature 32.6°C, and water distance 880m (extreme drought). The AI detects severe root dehydration and issues an Early Warning to trigger irrigation actuators to rescue crops. Ground-truth CSV marked \"Healthy\" due to biological latency (leaves have not yet yellowed). This represents the highest value of proactive IoT AI!",
    batchDeviationExplText2: "Should all 200,000 rows be rendered into the web DOM? Absolutely not! 200,000 rows × 21 columns = 4,200,000 HTML DOM nodes, consuming >3GB browser RAM and crashing the tab (Aw, Snap! Out of Memory). Industrial Big Data standards (Apache Spark df.show(20), BigQuery, Databricks) compute 100% in backend memory, rendering aggregated metrics and an interactive 25-row sample slice.",
    batchWeightSourceActiveLabel: "Active Model Weight Source:",
    batchWeightSparkSub: "Standard decision threshold T* = 0.50 | 30 independent distributed GBDT trees | Sharp probability resolution (1.39% - 96.65%)",
    batchWeightLgbSub: "Optimal ROC cutoff T* = 0.35 | Imbalance penalty scale_pos_weight = 6.24 | Bimodal distribution (18.6% - 54.0%)",
    batchBtnUseLgbWeights: "🟢 Use LightGBM Weights",
    batchBtnUseSparkWeights: "🔥 Use Apache Spark Weights",
    batchSelectedTag: "Active",
    batchSparkEmpiricalDiffTitle: "💡 Empirical distinction of Apache Spark MLlib: ",
    batchSparkEmpiricalDiffText: "Spark's distributed GBTClassifier uses 30 decision trees without forced positive weighting. Consequently, probabilities truthfully span 0% - 100%: Healthy plants register ~1.39% risk, while drought-stricken plants (such as row #3, soil moisture 7.87%) surge to 96.65%! Observe the \"Stress Prob\" column in the table below.",
    batchLgbEmpiricalDiffTitle: "💡 Empirical distinction of LightGBM SOTA: ",
    batchLgbEmpiricalDiffText: "Given the 97% healthy vs 3% diseased class imbalance, LightGBM applies scale_pos_weight = 6.24 to prioritize crop protection. Logit probabilities concentrate into two bimodal clusters: healthy plants around ~18.6% and stressed plants near ~54.0% (with optimal ROC cutoff T* = 35.0%). Click [🔥 Use Apache Spark Weights] above to observe the shift!",

    // Mobile QR & SQLite History Extra
    qrGenerating: "Generating QR Code...",
    dbNoRecords: "No field telemetry records saved yet.",
    actuatorAuditTitle: "Crop Rescue Actuator Audit Logs",
    actuatorAuditSubtitle: "actuator_logs table in SQLite — Complete audit trail of all triggered device commands",
    thCmdId: "Command ID",
    thDeviceName: "Device Name",
    thCmdType: "Command Type",
    thDuration: "Duration",
    thTriggeredBy: "Triggered By",
    thStatus: "Status",
    noActuatorsYet: "No actuators triggered yet.",
    statusSuccess: "Success",

    // Academic Hub Extra
    academicTradInferenceNote: "• Inference latency: < 20ms on Web & Mobile",
    academicTradArchNote: "• Architecture: Highly optimized Single-Node C++",
    academicSparkStructNote: "• Structure: 6 RDD Partitions (local[*])",
    academicSparkExecNote: "• Execution: Parallel DAG Stages via JVM",
    academicMathFidelityNote: "• Distributed execution preserves mathematical fidelity",
    academicMathBaselineNote: "• Both far surpass random baseline (0.50)",
    academicMathF1Note: "• F1-Score achieves robust 0.78 - 0.94",
    academicOverheadRamNote: "• Data < RAM: Single-node C++ wins due to zero overhead",
    academicOverheadOomNote: "• Data > RAM (Big Data): Sklearn crashes with OOM",
    academicOverheadScaleNote: "• Spark scales out horizontally across cluster nodes",
    academicAnalysis1Title: "Demystifying Distributed Overhead",
    academicAnalysis1P1: "Why does LightGBM take only 1.25s while Spark takes 21.4s?",
    academicAnalysis1P2: "The 200,000-row dataset is ~23.5 MB, fitting entirely inside RAM. At this scale, C++ (LightGBM) incurs zero network or memory partitioning overhead.",
    academicAnalysis1P3: "Meanwhile, Apache Spark MLlib must: 1) Initialize the Java Virtual Machine (JVM); 2) Serialize data through Py4J Gateway; 3) Hash-partition data into 6 Partitions and schedule DAG execution. This orchestration overhead exceeds raw calculation time.",
    academicAnalysis2Title: "When is Apache Spark MLlib Indispensable?",
    academicAnalysis2P1: "Single-Machine Out-Of-Memory (OOM) bottleneck:",
    academicAnalysis2P2: "When farm datasets accumulate over multiple seasons to 50GB or 500GB, loading into Pandas or Scikit-Learn will immediately crash due to RAM exhaustion.",
    academicAnalysis2P3: "Horizontal Scalability (Scale-out):",
    academicAnalysis2P4: "Apache Spark MLlib is not constrained by single-machine RAM. When data expands 10x, simply attach more Worker Nodes to the cluster to distribute partitions without modifying a single line of application code.",
    academicAnalysis3Title: "Standard Hybrid Architecture: Lambda Pattern",
    academicAnalysis3P1: "Batch Layer (Spark MLlib):",
    academicAnalysis3P2: "Runs scheduled nightly jobs on Hadoop / Databricks clusters to analyze massive historical archives, retrain models, and update global weights.",
    academicAnalysis3P3: "Speed Serving Layer (LightGBM Serving):",
    academicAnalysis3P4: "Embeds optimized models in FastAPI web servers to serve real-time slider adjustments with sub-20ms latency on Web and Mobile.",
    academicTrack1Badge: "Track 1: Raw Original Dataset",
    academicTrack1Title: "The 97% Accuracy Paradox",
    academicTrack1P1: "Dummy model achieves 96.91% Accuracy simply by predicting all crops as healthy. However, Recall and F1-Score are strictly 0.",
    academicTrack1P2: "Statistical analysis confirms the plant_health label is randomly distributed independently of the 9 environmental features (Zero-Signal). All AI algorithms stall at the random ROC-AUC floor of 0.50.",
    academicTrack2Badge: "Track 2: Standard Eco-Stress Label (SOTA)",
    academicTrack2DeployBadge: "Deployed to Web & Mobile",
    academicTrack2Title: "LightGBM Model Optimized at Decision Threshold T* = 0.34",
    academicTrack2P1: "Engineered 4 agronomic stress features (Acidification, Heat/Drought Shock, Hydrology, Pollution).",
    academicTrack2P2: "Model converges smoothly in 150 iterations, achieving ROC-AUC 0.83, Precision 95.05%, and F1-Score 0.778.",
    academicTrack2P3: "This core model is currently powering the Web Command Center & Mobile PWA.",
    academicRenderingChart: "📊 Chart rendering in progress...",

    // Mobile QR Sync & Standalone Mobile View
    mobileSyncTitle: "Mobile Field Station & Real-Time Bi-Directional Sync (QR Code)",
    mobileSyncDesc: "Scan QR code with smartphone camera to synchronize field sensors and trigger crop rescue actuators directly via WebSocket.",
    mobileWsReady: "WebSocket Ready (<50ms)",
    mobileWsWaiting: "Awaiting Connection",
    btnRecreateQR: "Regenerate QR Code",
    serverStatusRest: "REST API Server:",
    serverStatusDb: "Database Engine:",
    serverStatusWs: "Hub Connection:",
    qrSessionId: "Unique session ID (Persisted across tab switches)",
    qrLanIpLabel: "📡 Server LAN IP Address (for smartphone scanning):",
    btnOpenMobilePreview: "Open Mobile View Preview",
    wsLiveLogTitle: "Real-Time WebSocket Signal Stream",
    wsLatencyTip: "Latency < 50ms",
    mobileSimTitle: "1-Click Smartphone Data Simulation:",
    simFloodBtn: "🌊 Send Flood (92%)",
    simDroughtBtn: "☀️ Send Drought (18%, 38°C)",
    simAcidBtn: "🍋 Send Acid Soil (pH 4.2)",
    simOptimalBtn: "🌱 Send Optimal (pH 6.6, Moist 65%)",
    wsLogListening: "Listening for incoming smartphone connections...",
    dbHistoryTitle: "Field Telemetry & Diagnostic History in SQLite Database",
    dbHistorySubtitle: "sensor_diagnostics table in SQLite (Auto-refreshed instantly when Mobile dispatches data)",
    btnReloadTable: "Reload Table",
    btnExportCsv: "Export CSV",
    thId: "DB ID",
    thTime: "Timestamp",
    thSource: "Data Source",
    thPh: "pH",
    thMoisture: "Moisture",
    thTemp: "Temp",
    thStressProb: "Stress Prob",
    thRiskLevel: "Risk Level",
    thRemediation: "Prescribed Treatment",

    // Mobile Standalone View
    mobileHeaderTitle: "Farmer Mobile Field Station",
    mobileHeaderSubtitle: "Real-time bi-directional sync with Central Station",
    mobileBackToWeb: "← Return to Web Dashboard",
    mobileSyncToServerBtn: "Synchronize to Central Station",
    mobileSyncingBtn: "Synchronizing...",

    // Chatbot
    chatTitle: "AgriBot AI — Intelligent Agro-Physician",
    chatExpandedTip: "Full-screen expanded modal • Multi-turn conversational context",
    chatStandardTip: "Multi-turn conversational context preserved",
    chatApiKeyButton: "Enter Key",
    chatApiKeySaved: "API Key Loaded",
    chatApiKeyConfigTitle: "Configure Google Gemini API Key",
    chatApiKeySaveBtn: "Save Key",
    chatApiKeySavedToast: "API Key saved to browser storage!",
    chatModelSelectLabel: "AI Model Engine:",
    chatModelGemini: "Google Gemini Flash (Online Live Cloud Connection)",
    chatModelInternal: "Internal Agronomic Knowledge (Offline Zero-Cloud)",
    chatPlaceholder: "Ask about crops, soil acidity, micro-climate, pests...",
    chatSend: "Send",
    chatWelcome: "Hello! I am AgriBot — your smart agronomic physician for the AgriGuard-IoT system 🌿.\n\nAsk me anything regarding acidic soil, flood management, drought mitigation, NPK balance, or crop disease treatments!",
    chatNewSession: "New session started! Feel free to ask about plants and agricultural micro-climate 🌱",
    chatPrompt1: "How to treat soil suffering 92% severe waterlogging?",
    chatPrompt2: "Soil pH is 4.2 acidic; how much lime should be applied?",
    chatPrompt3: "Air temperature is 39°C; should I drench irrigation at noon?",
    chatThinking: "🌿 AgriBot is querying Google Gemini and synthesizing agronomic treatment...",
    btnMaximize: "Maximize chat window for full view",
    btnMinimize: "Minimize to standard corner window",
    btnRefreshChat: "Refresh and clear conversation",
    btnCloseChat: "Close chat",
  }
};

// Từ điển ánh xạ tự động cho câu chữ chẩn đoán Nông học sinh ra từ Backend
const AGRONOMY_PHRASES = [
  // Remediation sentences
  {
    vi: "Hệ sinh thái đang ở trạng thái tối ưu. Tiếp tục duy trì chế độ tưới tiêu và dinh dưỡng định kỳ theo lịch trình chuẩn.",
    en: "Ecosystem is in optimal equilibrium. Continue scheduled irrigation and balanced nutrient maintenance according to standard agronomic protocols."
  },
  {
    vi: "=== PHÁC ĐỒ CAN THIỆP NÔNG HỌC TỨC THÌ ===",
    en: "=== IMMEDIATE PRESCRIPTIVE AGRONOMIC PROTOCOLS ==="
  },
  {
    vi: "• Xử lý chua đất: Rải vôi bột nông nghiệp (CaCO3) liều lượng 350-450 kg/ha, tưới ẩm nhẹ để trung hòa nhanh tầng đất mặt.",
    en: "• Acidic Soil Remediation: Broadcast agricultural lime (CaCO3) at 350-450 kg/ha, followed by light irrigation to rapidly neutralize topsoil acidity."
  },
  {
    vi: "• Hạ kiềm: Bổ sung thạch cao nông nghiệp (CaSO4) hoặc phân hữu cơ vi sinh giàu axit humic để kéo pH về mức 6.2 - 6.8.",
    en: "• Alkaline Reduction: Apply agricultural gypsum (CaSO4) or humic-rich organic microbial fertilizer to adjust soil pH to 6.2 - 6.8."
  },
  {
    vi: "• Cấp cứu hạn & sốc nhiệt: Bật phun sương làm mát 10-15 phút để hạ nhiệt tán lá; tưới nhỏ giọt vào sáng sớm hoặc chiều mát; phủ rơm rạ giữ ẩm vùng gốc.",
    en: "• Heatwave & Drought Emergency: Activate canopy misting for 10-15 mins to alleviate leaf heat shock; run drip irrigation in early morning/dusk; mulch root-zone with straw."
  },
  {
    vi: "• Cấp cứu ngập úng: Kích hoạt bơm tiêu úng và mở van xả rãnh ngay lập tức; sau khi rút nước xới nhẹ mặt luống phá váng và tưới nấm Trichoderma phòng thối rễ.",
    en: "• Waterlogging Emergency: Trigger drainage pump and open trench floodgates immediately; lightly cultivate surface soil after drawdown to break crust, and apply Trichoderma against root rot."
  },
  {
    vi: "• Bù ẩm cho lúa: Bơm nước vào ruộng đạt mực nước 3-5cm để dưỡng cây làm đòng, tránh thất thoát hạt.",
    en: "• Rice Water Replenishment: Pump water into paddy to maintain 3-5cm depth to support panicle development and prevent yield reduction."
  },
  {
    vi: "• Giảm tác động ô nhiễm: Phun bổ sung phân bón lá chứa Axit Amin và vi lượng để kích thích cơ chế tự miễn dịch của biểu bì lá.",
    en: "• Mitigate Pollution Impact: Spray foliar fertilizer containing Amino Acids and micronutrients to stimulate leaf cuticle immunity."
  },
  {
    vi: "• Cải thiện ánh sáng: Cắt tỉa cành vô hiệu, dọn dẹp cỏ dại che bóng tán lá.",
    en: "• Improve Photosynthetic Light: Prune unproductive canopy shoots and remove weeds shading the leaves."
  },
  {
    vi: "• Che phủ bảo vệ đất: Trồng xen cây họ đậu hoặc phủ thảm xác thực vật để chống xói mòn và giữ ẩm tầng mặt.",
    en: "• Soil Cover Protection: Intercrop legumes or mulch crop residues to prevent soil erosion and conserve topsoil moisture."
  },
  {
    vi: "⚠️ MỨC ĐỘ NGUY CẤP: Kỹ sư trạm thực địa cần lập tức kích hoạt thiết bị cứu cây và gửi thông báo khẩn cấp tới nông hộ qua ứng dụng di động.",
    en: "⚠️ CRITICAL ALERT: Field engineer must immediately trigger crop rescue actuators and broadcast emergency mobile alerts to local farmers."
  },

  // Root causes pattern translations
  {
    vi: "Đất bị chua/axit hóa nghiêm trọng",
    en: "Severe soil acidification"
  },
  {
    vi: "gây bất hoạt vi sinh vật và khóa hấp thụ rễ.",
    en: "inactivating beneficial microbes and locking root nutrient uptake."
  },
  {
    vi: "Đất bị kiềm hóa",
    en: "Soil alkalization"
  },
  {
    vi: "làm kết tủa sắt, phốt pho và các vi lượng thiết yếu.",
    en: "causing precipitation of iron, phosphorus, and essential micronutrients."
  },
  {
    vi: "Cặp đôi stress sốc nhiệt & hạn hán: Nhiệt độ",
    en: "Dual heatwave & drought stress: Air temperature"
  },
  {
    vi: "kết hợp độ ẩm đất kiệt quệ",
    en: "combined with depleted soil moisture"
  },
  {
    vi: "Độ ẩm đất quá thấp",
    en: "Soil moisture is critically low"
  },
  {
    vi: "chạm ngưỡng héo rũ vĩnh viễn của tế bào thực vật.",
    en: "reaching permanent wilting point of plant cellular tissue."
  },
  {
    vi: "Độ ẩm đất ngập úng nghiêm trọng",
    en: "Severe soil waterlogging"
  },
  {
    vi: "gây yếm khí tầng rễ, cạn kiệt oxy hòa tan và tăng nguy cơ nấm thối rễ.",
    en: "causing root-zone anoxia, depleting dissolved oxygen, and heightening fungal root rot risk."
  },
  {
    vi: "Rau màu rễ nông mẫn cảm cao với ẩm độ",
    en: "Shallow-rooted vegetables highly vulnerable to excessive moisture"
  },
  {
    vi: "Nguy cơ nghẹt rễ thối cổ rễ nhanh chóng.",
    en: "Risk of rapid root suffocation and collar rot."
  },
  {
    vi: "Lúa nước thiếu hụt nước nghiêm trọng",
    en: "Wet rice experiencing severe water deficit"
  },
  {
    vi: "Nguy cơ nghẹt đòng và khô cháy chóp lá.",
    en: "Risk of impaired panicle emergence and leaf tip scorch."
  },
  {
    vi: "Tiểu khí hậu mùa Hè nắng gắt",
    en: "Intense Summer micro-climate sunshine"
  },
  {
    vi: "thúc đẩy tốc độ bốc thoát hơi nước vượt ngưỡng bù ẩm tự nhiên.",
    en: "driving evapotranspiration beyond natural moisture replenishment."
  },
  {
    vi: "Thời tiết mùa Đông lạnh",
    en: "Cold Winter climate"
  },
  {
    vi: "làm chậm tốc độ trao đổi chất và hô hấp của hệ rễ.",
    en: "retarding metabolic turnover and root respiration."
  },
  {
    vi: "Chỉ số ô nhiễm không khí/nguồn nước báo động",
    en: "Alarming environmental/water pollution index"
  },
  {
    vi: "phá vỡ màng khí khổng.",
    en: "disrupting stomatal membrane function."
  },
  {
    vi: "Số giờ nắng không đủ",
    en: "Insufficient sunlight hours"
  },
  {
    vi: "làm suy giảm năng suất quang hợp.",
    en: "curtailing photosynthetic capacity."
  },
  {
    vi: "Mật độ thảm thực vật che phủ quá thấp",
    en: "Vegetation canopy density too sparse"
  },
  {
    vi: "khiến tầng đất mặt trơ trọi, bốc hơi nước mạnh.",
    en: "leaving bare topsoil vulnerable to extreme evaporation."
  },
  // Actuator names
  {
    vi: "Trạm Phun Sương Làm Mát Vùng 1",
    en: "Zone 1 Canopy Cooling Misting"
  },
  {
    vi: "Phun Sương Làm Mát Vùng 1",
    en: "Zone 1 Canopy Cooling Misting"
  },
  {
    vi: "Máy Bơm Tưới Nhỏ Giọt Vùng Gốc",
    en: "Root-Zone Drip Irrigation Pump"
  },
  {
    vi: "Máy Bơm Tưới Gốc",
    en: "Root-Zone Drip Irrigation Pump"
  },
  {
    vi: "Máy Bơm Tiêu Úng & Van Xả Rãnh",
    en: "Emergency Drainage Pump & Floodgate"
  },
  {
    vi: "Máy Bơm Tiêu Úng & Van Xả",
    en: "Emergency Drainage Pump & Floodgate"
  },
  {
    vi: "Còi Báo Động & Đèn Chớp Thực Địa",
    en: "Field Sirens & Strobe Emergency Lights"
  },
  {
    vi: "Còi Báo Động & Đèn Chớp",
    en: "Field Sirens & Strobe Emergency Lights"
  },
  // Crop names
  {
    vi: "Lúa nước",
    en: "Wet Rice"
  },
  {
    vi: "Cây ăn trái",
    en: "Fruit Trees"
  },
  {
    vi: "Rau màu thổ nhưỡng",
    en: "Vegetables"
  },
  {
    vi: "Đồng cỏ chăn nuôi",
    en: "Pasture Grass"
  }
];

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('agri_lang') || 'vi');

  const toggleLanguage = () => {
    const nextLang = lang === 'vi' ? 'en' : 'vi';
    setLang(nextLang);
    localStorage.setItem('agri_lang', nextLang);
  };

  const t = (key) => {
    return dictionary[lang]?.[key] || key;
  };

  // Helper dịch động văn bản Nông học từ Backend (Root Causes, Remediation, etc.)
  const tText = (text) => {
    if (!text || typeof text !== 'string') return text;
    if (lang === 'vi') return text;

    let translated = text;
    for (const item of AGRONOMY_PHRASES) {
      if (translated.includes(item.vi)) {
        translated = translated.replaceAll(item.vi, item.en);
      }
    }
    return translated;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t, tText }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
